language: c
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make -C Debug ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "mhoIxFRoCertWX18DUQm/vAqE1L38q8swAISf0AV9HBLO6yXK/8mNOf19Uc+9qxsqJNug9wo9nl6eGwaZTQU+eTLKQIw/2Z73UqWPIw5H1WFKaSfPnR1FCmFPIR2faKFz0vcgSQKGrwAYhf/q7AEtkOoP1Ptxl+d3MRQgxCliPNXqYVWCWj7TmIbdGFNRyzpJh9w+AKGDiJ6AjT2SiLg+ZjTZbaIdK0l/czbcGh8ufV30x2m1Cp56FnsKicuJwXr72aLMf8qki/XhDCTYoi/oG6f3lIxthgPH0H9aYeyuhCDg6Hfr241QpkaTWjK3UHCy8uXZtIV82n4y9QF21CKILzcRjx53rJp1ujcb6qe6bD8/q7VvmmB20mfdA/QaQlQMy1rMB7lzSXnKect+h0frO35yk4IU04VJU4CwsMfEGcn0Qoi1kEgjWGYAFgLndRDkJo4OpjM4Zvc5skjao4He0lKVzYB8Wqe1a3t+RRFYE/SE40dgtH86Q7CEHzzcfCz0iP1EdNppowCkdWD5spI7lwYsTKMNh2l2G8EE7tEV9mZMBlQd7N/jgMBvfiy28/gYfqGnsN8U7S0QCDGQnFf0cn0A+rTbq8idbJNsQgjQ/iYFfVCm+7k7JEWT4WbuwFdssDsNPUIKRbGNGvmFLCObHShPpSBWm5NXpvXQSdKsoE="
 
before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Erguotou/coverity2"
      description: "Coverity playground"
    notification_email: jeromeliang@hotmail.com
    build_command_prepend: "make -C Debug"
    build_command: "make -C Debug"
    branch_pattern: coverity_scan