language: c
script: make -C Debug

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TvhWbqU5+Kv0yeh7UzfK2Vh+ZGBma6M3kiG4g827N9ob9AjIW5Odt9Q1M+tcdYnJ5o2KpVsadSilTk8yGbZahaxifWvfvJ3AFeUHoqu47Wk6JcMEc/T/VumHHjsVgNqNXptmEzBIuLNnpNAdry90JSbnVr9BU7Ybo+pZQgXarFJqgVHsmUAAJpUBpkCjj5zN20H32ziKJoO1qiN+t8kJIgG/7Ajp9llpM1Xezrrtgv1FIfqm9ieEiID/LVIXQ5jGXyf88z8mei/rwra1pOpnK+Fui9A+CjgUIz+t2F7wgskfNYE9C1ZTBBdyiEDxs/nA/ybw5a1Ktm0Gu8V+3yfgc8SbuhlskEdXcjguHCCafG9lWiFK+FzV4huqMdWubQatgmaSw9yhi2VpwN3ZzSSFgH5PXTN2GjupimaAn/jLtmRoKBtLjamhq4UmjkpgC3ilFS/j2+960SVyqGO35IE75rGAQ99VHNlEvKxvAZxn7XHhUuCXRMcM6uSzPrDtpI9s8URHaexCk9PdXx6PMkR7ltB3gY0BA4/RI9kOLwiiZ3l4lXo/0ZS7ucs+Wcznkk2OmW04hAP6l5Ck0fWJok98QyuqbDzfzsgUCkuTmBMGRcreXTKT/8GPC9knhy19YSNKZHZSYAVIHQUJQoP+/nmUUgTpt3JxEQZMlWDd2day35A="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Erguotou/coverity2"
      description: "<Your project description here>"
    notification_email: jeromeliang@hotmail.com
    build_command_prepend: ""
    build_command: "make -C Debug"
    branch_pattern: master